### ISSUE TITLE
yapapi: Delete allocations only after a payment is confirmed

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/goth#241]
Currently, allocations are deleted immediately after a payment is created and subsequent confirmation of a payment causes an error in yagna payments API (query error: foreign key constraint failed)

To address

**Comment by stranger80** [comment]
...is this still relevant?

**Comment by shadeofblue** [comment]
exactly @azawlocki

**Comment by azawlocki** [comment]
@shadeofblue @shadeofblue Hard to say. AFAIK the allocations are associated with an instance of `Executor` and are released when the instance is shut down (i.e. when leaving the scope of `async with Executor()...`). That makes sense to me, since after shutting down the `Executor` incoming invoices will not be accepted anyway. 

I think it has always been this way but perhaps there were errors that prevented `Executor` instances from being shut down cleanly? If so, those errors are most likely fixed by now and I'd say we should close this issue.
